### ISSUE TITLE
Testing Result

### ISSUE THREAD

**Issue by tianyuan88995516** [facebook/wdt#68]
I have made some test on AWS environment and found the bottleneck is about 50 MB/S
in the test environment, i have use AWS c3.large machine, and use for local storage, the test location is Frankfurt Sending and Singapore Receiving, and i got some question want to asked 
1. When i try to using 256 socket have a try, there are a lot of sockets are time-out, i am not sure it is because of what, is there any place to find the reason of timeout.? and is it caused by network issues?
2. During the testing, i using dstat for monitoring system I/O, the send/read; receive/write is different, any compress have been used during transport? and also, i have observer a situation, after about 20 second latter the receiver side (receive/write) has been increase, the sender start to transfer the file, i am not quite sure about is there any pre- action has been taken?

**Comment by tianyuan88995516** [comment]
Update:

I have used the commend as follow 
Sender Side:
wdt -directory /mnt/testdata -destination * -num_ports 128 -transfer_id 123456789
Reciver Side:
wdt -directory /mnt/test -num_ports 128 -run_as_daemon -transfer_id 123456789

**Comment by ldemailly** [comment]
128 is probably way too high. anything above 20-30 is probably unnecessary. Also if your source isn't in cache or in flash, it's unlikely that you get a great throughput (you will for instance be limited by your disk read speed/bandwidth and not the network on systems with a single hard disk - for that you should use -option_type=disk which will revert to single thread)

timeout could be either because of network or because you overwhelm the writer IOs 

you can turn on -enable_perf_stat_collection which can give a clue as which part is the time being spent and paste the result here

**Comment by ldemailly** [comment]
any update on your testing @tianyuan88995516 ?

**Comment by ldemailly** [comment]
please reopen if you have problems and share your results in any case
